site_name: Tasmota
site_description: Documentation (Wiki) for Tasmota
site_url: https://tasmota.github.io/docs/
repo_name: 'arendst/tasmota'
repo_url: 'https://github.com/arendst/tasmota'
edit_uri: 'https://github.com/tasmota/docs/blob/master/docs/'
docs_dir: docs
# copyright: 'Copyright &copy; 2020 Tasmota Development Team'

plugins:
  - search:
      lang:
        - de
        - en
  - alternate-link
  - minify:
      minify_html: true
  - redirects:
      redirect_maps:
        'GPIO-Locations.md': 'Pinouts.md'
        'BMP280.md': 'BME280.md'
        'Rule-Cookbook.md': 'Rules.md'
        'Sensor-Configuration.md': 'Peripherals.md'
        'Scripting-Cookbook.md': 'Scripting-Language.md'
        'Status-LED.md': 'Lights.md'
        'Tuya-Protocols.md': 'TuyaMCU.md'
        'Upgrade.md': 'Upgrading.md'
# - htmlproofer

strict: true

theme:
  name: material
  language: 'en'
  # custom_dir: 'overrides'
  logo: '_media/logo.svg'
  favicon: _media/favicon.ico
  palette:
    primary: 'blue'
    accent: 'indigo'
    scheme: preference
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
  font:
    text: Barlow
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/discord
      link: 'https://discord.gg/Ks2Kzd4'
    - icon: fontawesome/brands/telegram
      link: 'https://t.me/tasmota'
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/tasmota'
markdown_extensions:
  - admonition
  - toc:
     permalink: "~"
     toc_depth: 3
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.emoji:
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.highlight
  - pymdownx.superfences
  - meta

google_analytics:
  - 'UA-140681905-2'
  - 'auto'

extra_css:
  - 'assets/css/anchor-fix.css'

nav:
  - Home:
    - News: index.md
    - About.md
    - Getting Started: Getting-Started.md
    - Upgrading.md
    - MQTT.md
    - Commands: Commands.md
    - Templates: Templates.md
    - Components.md
    - Modules: Modules.md
    - Peripherals: Peripherals.md
    - WebUI.md
    - Compiling: Compile-your-build.md
    - Contributing: Contributing.md
    - Download.md
    - Project Showcase: "https://github.com/arendst/Tasmota/discussions/categories/show-and-tell"
  - Features:
    - Introduction: Features.md
    - Bluetooth.md
    - Buttons-and-Switches.md
    - DeepSleep.md
    - Device-Groups.md
    - Dynamic-Sleep.md
    - I2C Devices: I2CDevices.md
    - IR Communication: Tasmota-IR.md
    - Lights.md
    - OpenTherm: OpenTherm.md
    - PIR-Motion-Sensors.md
    - Power-Monitoring-Calibration.md
    - PWM-dimmer-switch.md
    - RF 433MHz Protocol: RF-Protocol.md
    - Rules.md
    - Scripting: Scripting-Language.md
    - Serial-to-TCP-Bridge.md
    - Blinds-and-Shutters.md
    - Smart-Meter-Interface.md
    - Subscribe-&-Unsubscribe.md
    - TasmotaClient.md
    - Thermostat.md
    - Timers.md
    - TLS.md
    - TuyaMCU.md
    - Zigbee.md
    - Projects and Tutorials: Tutorials.md
    - For Developers: For-Developers.md
  - Smart Home Integrations:
    - Introduction: Integrations.md
    - Alexa.md
    - AWS-IoT.md
    - Domoticz.md
    - Home-Assistant.md
    - Homebridge.md
    - HomeSeer.md
    - IP-Symcon.md
    - KNX.md
    - NodeRed.md
    - nymea.md
    - Octoprint.md
    - openHAB.md
    - otto.md
    - IOBroker: "https://github.com/arendst/Tasmota/issues/3769"
    - Mozilla WebThings Adapter: "https://github.com/tim-hellhake/tasmota-adapter"
    - SmartThings: "https://github.com/hongtat/tasmota-connect"
  - Peripherals:
    - Supported-Peripherals.md
    - Analog pin: ADC.md
    - Buzzer.md
    - Displays.md
    - ESP32.md
  - Supported Devices:
    - Configure Unknown Device: Configuration-Procedure-for-New-Devices.md
    - All Supported Devices: https://templates.blakadder.com/ "target=_blank"
    - Wi-Fi Module Pinouts: Pinouts.md
    - Supported-Modules.md
  - Help:
    - FAQ.md
    - Troubleshooting.md
    - Device-Recovery.md
    - Discord Support: https://discord.gg/Ks2Kzd4 "target=_blank"
  - Builds.md
