version: 2.1

orbs:
  python: circleci/python@2.0.3

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: cimg/python:3.10.6
      
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip && pip install --upgrade -r requirements.txt
            pip install pytz --upgrade
            pip install tzdata --upgrade

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}

      - deploy:
          name: "Deploy docs"
          command: |
            git clone --branch=master --depth=1 "https://$USER_NAME:$GITHUB_TOKEN@github.com/tasmota/$CIRCLE_PROJECT_REPONAME.git" deploy && cd deploy
            git clone --branch=gh-pages --depth=1 "https://$USER_NAME:$GITHUB_TOKEN@github.com/tasmota/$CIRCLE_PROJECT_REPONAME.git" site
            . ../venv/bin/activate
            mkdocs build
            cp -r .circleci site/.circleci
            cd site
            git config user.name "$USER_NAME"
            git config user.email "$USER_EMAIL"
            git add --all
            git commit -m "CircleCI deploy no. $CIRCLE_BUILD_NUM [ci skip]"
            git push --force origin gh-pages
