name: build
on:
  push:
    branches:
      - main
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: pip install mkdocs
      - run: pip install --upgrade -r requirements.txt
      - run: |
          sudo ln -fs /usr/share/zoneinfo/Europe/Oslo /etc/localtime
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --no-install-recommends tzdata
          sudo dpkg-reconfigure --frontend noninteractive tzdata
      - run: mkdocs gh-deploy --force --clean --verbose
